name: Variables
run-name: Aprendiendo de variables
on: push
env:
    DAY_OF_WEEK: Sunday

jobs:
    usando_variables:
        runs-on: ubuntu-latest
        env:
            HI_BRO: "What supppppppppp"
        steps:
            - name: Lets say hi
              run: echo "$BRO_NAME(${{ github.actor }}) $HI_BRO, its $DAY_OF_WEEK."
              env:
                BRO_NAME: Julian
